### PR TITLE
Added Daniel Miranda to team file

### PR DESCRIPTION
**Pull request by dmiranda2791**

### CODE REVIEW

**Comment by rsiwady29** [comment]
@dmiranda2791 This needs a rebase.

**Comment by bsommardahl** [comment]
@dmiranda2791 Hey man. We don't need the photo in the repo for this. The photo actually comes from gravatar. As long as your avatar is there, then it shows up here. Please remove the photo from this PR. Also, as @rsiwady29 said, it needs to be rebased to clear up the merge conflict.

**Comment by rsiwady29** [comment]
yeah @bsommardahl Currently pairing with @camilorivera and @dmiranda2791 to fix this.

**Comment by dmiranda2791** [comment]
@bsommardahl We are done here. Thanks @rsiwady29

**Pull request merged**
